#!/bin/bash

# 1. ensure /etc/cpanel/ea4/profiles/cpanel exists and is empty
rm -rf /etc/cpanel/ea4/profiles/cpanel
mkdir -p /etc/cpanel/ea4/profiles/cpanel

SERVER_TYPE=$(readlink -n /usr/local/cpanel/server.type);
num=`ls -1 /opt/cpanel/ea-profiles-cpanel/server-type-$SERVER_TYPE-*.json 2> /dev/null | wc -l`
if (( $num > 0 )); then
    # 2. Make symlinks in /etc/cpanel/ea4/profiles/cpanel/ to profiles with the name likeness of server-type-$SERVER-TYPE-*.json
    #    - The symlinks are what will be available to EA4 UI/CLI.
    #    - There should always be /etc/cpanel/ea4/profiles/cpanel/default.json
    #    - if the name is server-type-XYZ-default.json, the final profile will have the name default.json

    echo "Doing “$SERVER_TYPE” mode EA4 default profile."
    for profile in `ls -1 /opt/cpanel/ea-profiles-cpanel/server-type-$SERVER_TYPE-* | perl -n -e 'if (m/server-type-[^-]+-([^-]+\.json)/) { print "$1\n"; }'`
    do
        ln -s /opt/cpanel/ea-profiles-cpanel/server-type-$SERVER_TYPE-$profile /etc/cpanel/ea4/profiles/cpanel/$profile
    done
else
    # 2. Make symlinks in /etc/cpanel/ea4/profiles/cpanel/ to profiles in /opt/cpanel/ea-profiles-cpanel/
    #    - The symlinks are what will be available to EA4 UI/CLI.
    #    - There should always be /etc/cpanel/ea4/profiles/cpanel/default.json

   echo "Doing standard EA4 profiles."
   pushd /opt/cpanel/ea-profiles-cpanel/ > /dev/null

    for profile in `ls *.json | grep -v server-type-`; do
        ln -s /opt/cpanel/ea-profiles-cpanel/$profile /etc/cpanel/ea4/profiles/cpanel/$profile
    done

   popd > /dev/null
fi

