name: Publish to external sites

on:
  push:
    branches:
      - main
      - production
      - 2025-03.pek.*  ## WIP
jobs:
  build:
    uses: webpros-cpanel/ea-tools/.github/workflows/reusable-external-publish.yml@2025-03.pek.ZC-12670.cpanelinc  ## ghes
    secrets: inherit
